### Numpy array vs python lists

In [3]:
import numpy as np
import time

In [2]:
size = 100_000_000 # 100 million

py_list = list(range(size))
start = time.time() # start time
sq_list = [x**2 for x in py_list]
end = time.time() # end time

print(f"Python list time : {end-start} seconds")

np_array = np.array(py_list)
start = time.time() # start time
sq_array = np_array ** 2 # vectorization
end = time.time() # end time

print(f"numpy array time : {end-start} seconds")

Python list time : 3.8704440593719482 seconds
numpy array time : 0.412869930267334 seconds


In [3]:
import sys

print(f"size of python list : {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"size of numpy array : {np_array.nbytes} bytes")



size of python list : 80000005600000000 bytes
size of numpy array : 800000000 bytes


# Creating numpy arrays

In [4]:
# create from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"krish"])
print(arr2, type(arr2), arr2.shape)

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'krish'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# create from scratch
arr = np.zeros((2,3), dtype = "int64") # prefill with zeroes
print(arr, arr.shape)

arr2 = np.ones((2,3), dtype = float) # prefill with one
print(arr2, arr2.shape)

arr3 = np.full((6,), 7) # prefill with a value
print(arr3, arr3.shape)

arr4 = np.eye(2) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,10,2) # just like range(start,end,step)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[7 7 7 7 7 7] (6,)
[[1. 0.]
 [0. 1.]] (2, 2)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


# Numpy array properties

In [12]:
arr = np.array([[1,2],[3,4],[5,6]])

print(arr.shape) # for dimensions (m*n)
print(arr.size) # total elements of the array
print(arr.dtype) # data type of the array
print(arr.ndim) # no. of dimensions

float_arr = arr.astype(np.float64) # type conversion from int64 to floar
print(float_arr)


(3, 2)
6
int64
2
[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Operations on Numpy arrays

In [18]:
# 1. reshaping (change dimensions of an existing array)

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flatten_array = arr.flatten()             # flattens into 1d array
print(flatten_array, flatten_array.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [23]:
# 2. Indexing 

arr = np.array([1,2,3,4,5])
print(arr[0]) # 1st element
print(arr[4]) # 5th element

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[2][2]) # 3rd number of the 3rd element

1
5
9


In [4]:
# 3. Fancy Indexing : accessing a set of values in one command

index = [0,2,4]
arr = np.array([1,2,3,4,5])
print(arr[index])

[1 3 5]


In [5]:
# 4. Boolean Indexing : indexing but with a boolen condition

arr = np.array([1,2,3,4,5])
print(arr[arr>3])

[4 5]


In [11]:
# 5. slicing : [start:end(not included):step]
# in python list, a copy is created for slicing but in numpy a view is created
arr = np.array([1,2,3,4,5])
print(arr[0:4])
print(arr[0:])
print(arr[:2])
print(arr[:-1])
print(arr[::2])

[1 2 3 4]
[1 2 3 4 5]
[1 2]
[1 2 3 4]
[1 3 5]


# Multi-Dimensional Arrays

In [24]:
# used for many things, but basically very useful for computer vision

In [ ]:
# 2D arrays : black and white photos [axis 0 = rows and axis = columns]

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(arr2d.sum()) # sum of all elements
sum_of_cols = np.sum(arr2d, axis = 0) # here to claculate value of each col, we use axis = 0(rows), confusing but try to visualise
print(sum_of_cols)
sum_of_rows = np.sum(arr2d, axis = 1) # here to claculate value of each rows, we use axis = 1(cols), confusing but try to visualise
print(sum_of_rows)
print(arr2d[0:2,1:2]) # slicing of 2d arrays using axis(rows and columns)

In [31]:
# 3D arrays : color photos [axis 0 = layer, axis 1 = rows, axis 2 = columns]
# This topic is veru confusing so study and practice carefully
# we create 2 arrays inside 1 array to make a 3d array

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2(layers) * 3(cols) * 2(rows) array
print(arr3d, arr3d.shape)

print(arr3d[1,1,0]) # indexing, gives us the exact element
print(arr3d[:,0,:]) # slicing, it will give us both the first rows from the 2 layers
print(arr3d[:,:,0]) # slicing, it will give us both the first cols from the 2 layers
arr3d[:,0,:] = 67 # to change the values of both first rows of the 2 layers
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[67 67]
  [ 3  4]
  [ 5  6]]

 [[67 67]
  [ 9 10]
  [11 12]]]


In [6]:
# Vector Normalisation : transforming the values of an array so that they fit into a range but dont their properties
# like 0 to 1 for probability and many more but we will learn about
# std normalisation : ((arr(value) - mean)/std deviation) where std deviation = root((sum(arr(value)-mean)^2) / no. of elements)

arr2d = np.array([[1,2],[3,4]])
print(arr2d)

mean = np.mean(arr2d)
std_dev = np.std(arr2d)

norm_arr = (arr2d-mean)/std_dev
print(norm_arr)

print(np.mean(norm_arr)) # mean of the normalized array will be 0
print(np.std(norm_arr)) # std deviation of normalized array will be 1


[[1 2]
 [3 4]]
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0


In [ ]:
%